%% Train the model of two layers
function pars=temp_hiear_train(pars)

if pars.layer1_from_existed_data || pars.layer1_using_existed_data
    load(pars.layer1_existed_data);
end

if ~pars.layer1_using_existed_data

    wxf_13      = []; wxf_12    = [];
    wyf_13      = []; wyf_12    = [];
    whf_13      = []; whf_12    = [];
    wy_13       = []; wy_12     = [];
    wh_13       = []; wh_12     = [];
    
    if pars.layer1_from_existed_data
        wxf_13  = layer1_13_pars.wxf; wxf_12    = layer1_12_pars.wxf;
        wyf_13  = layer1_13_pars.wyf; wyf_12    = layer1_12_pars.wyf;
        whf_13  = layer1_13_pars.whf; whf_12    = layer1_12_pars.whf;
        wy_13   = layer1_13_pars.wy;  wy_12     = layer1_12_pars.wy;
        wh_13   = layer1_13_pars.wh;  wh_12     = layer1_12_pars.wh;
    end

    layer1_13_pars     = factor_GBM_train(pars.train_data_f1, ...
                                pars.train_data_f3, ...
                                'numfactors', pars.layer1_numfactors, ...
                                'batchsize', pars.layer1_batchsize, ...
                                'batchOrderFixed', pars.layer1_batchOrderFixed,...
                                'nummap', pars.layer1_nummap, ...
                                'numepoch', pars.layer1_numepoch, ...
                                'wxf', wxf_13, 'wyf', wyf_13, 'whf', whf_13, ...
                                'wy', wy_13, 'wh', wh_13, ...
                                'display', pars.layer1_13_display, ...
                                'display_figure', pars.layer1_13_figure, ...
                                'saveFile',false, 'seed', 0);

    layer1_12_pars     = factor_GBM_train(pars.train_data_f1, ...
                                pars.train_data_f2, ...
                                'numfactors', pars.layer1_numfactors, ...
                                'batchsize', pars.layer1_batchsize, ...
                                'batchOrderFixed', pars.layer1_batchOrderFixed,...
                                'nummap', pars.layer1_nummap, ...
                                'numepoch', pars.layer1_numepoch, ...
                                'wxf', wxf_12, 'wyf', wyf_12, 'whf', whf_12, ...
                                'wy', wy_12, 'wh', wh_12, ... 
                                'display', pars.layer1_12_display, ...
                                'display_figure', pars.layer1_12_figure, ...                               
                                'saveFile',false, 'seed', 0);                        

    save(pars.layer1_save, 'layer1_13_pars', 'layer1_12_pars'); 
end

pars.layer1_13_pars     = layer1_13_pars;
pars.layer1_12_pars     = layer1_12_pars;
